openapi: 3.0.3
info:
  title: Auth Service API
  version: 1.0.0
servers:
  - url: http://localhost:3001
paths:
  /login:
    post:
      summary: Authenticate with identifier and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [identifier, password]
              properties:
                identifier: { type: string, example: admin@example.com }
                password: { type: string, example: Secret123! }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token: { type: string }
                  user:
                    type: object
                    properties:
                      id: { type: string }
                      username: { type: string }
                      email: { type: string }
                      role: { type: string }
        '400': { description: Bad Request }
        '401': { description: Unauthorized }
  /validate:
    get:
      summary: Validate JWT
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  isValid: { type: boolean, example: true }
                  sub: { type: string }
                  role: { type: string }
                  username: { type: string }
                  iat: { type: integer }
                  exp: { type: integer }
        '401': { description: Unauthorized }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
