openapi: 3.0.3
info:
  title: User Service API
  version: 1.0.0
paths:
  /register:
    post:
      summary: Register a user (admin/receptionist only)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
            examples:
              valid:
                value:
                  username: john_doe
                  email: john@example.com
                  document: 12345678900
                  phone: "+5511999999999"
                  password: StrongPass1
                  role: guest
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Duplicate email/document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /self-register:
    post:
      summary: Public self register (forces role=guest)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
            examples:
              valid:
                value:
                  username: guest1
                  email: guest1@example.com
                  document: 12345678900
                  phone: "+5511888888888"
                  password: StrongPass1
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Duplicate email/document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    RegisterRequest:
      type: object
      required: [username, email, document, phone, password]
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        document:
          type: string
          description: CPF/RG digits only
        phone:
          type: string
          description: E.164 format preferred
        password:
          type: string
          format: password
        role:
          type: string
          enum: [guest, receptionist, admin]
    UserResponse:
      type: object
      properties:
        id: { type: string }
        username: { type: string }
        email: { type: string }
        role: { type: string }
        document: { type: string }
        phone: { type: string }
        active: { type: boolean }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
    Error:
      type: object
      properties:
        error:
          type: string
